services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio.local
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio.local
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio.local
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio.local:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      "