services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    entrypoint: |
      /bin/sh -c '
      cd /home/iceberg
      pip install duckdb --upgrade
      python /opt/spark/scripts/generate_data.py
      '
    networks:
      iceberg_net:
    volumes:
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./generate_data.py:/opt/spark/scripts/generate_data.py
    ports:
      - 8888:8888
      - 10000:10000
      - 10001:10001