services:
  minio:
    extends:
      file: composes/minio.yml
      service: minio
    environment: &aws-credentials
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1

  mc:
    extends:
      file: composes/minio.yml
      service: mc
    environment:
      <<: *aws-credentials

  rest:
    extends:
      file: composes/tabular-rest.yml
      service: rest
    environment:
      <<: *aws-credentials

  spark-iceberg:
    extends:
      file: composes/tabular-ingest.yml
      service: spark-iceberg
    environment:
      <<: *aws-credentials
      PYTHONUNBUFFERED: 1
    depends_on:
      - rest
      - mc
      - minio
    volumes:
      - ./configs/tabular_ingest/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./configs/tabular_ingest/generate_data.py:/opt/spark/scripts/generate_data.py
  jupyter:
    extends:
      file: composes/jupyter.yml
      service: jupyter
    volumes:
      - ./notebooks:/home/jovyan/examples/

networks:
  iceberg_net: 